name: GitHub Actions Demo

on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 
      
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      
      #Output the name of the event that triggered the workflow
      - run: |
          echo "Ecent Name: ${{ github.event_name }}"
          echo "Branch ${{ github.ref }}."
      
      #Output the name of the branch that the repository is currently referencing
      - uses: actions/checkout@v4.1.0
      #List all files in the repository
      - name: List files in the repository
        run: |
          echo "Files of ${{ github.repository }}:"
          tree

      # Print directories
      - uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2

    
    
    
